### ISSUE TITLE
Release specification to create new runtimes

### ISSUE THREAD

**Issue by pakoito** [inkle/ink#3] opened 2016-03-12 02:31 UTC
If you want ink to succeed it'd be better if you provided either new backends or a spec to create them. At least a specification or json schema would be appreciated.

**Comment by joethephish** [comment] 2016-03-12 10:33
Thanks for the suggestion! Right now it's really early days for us - we're in alpha, and the runtime is subject to change, so we should wait for the runtime to be completely stable before we think about creating a spec. Any spec we would create right now would easily get out of sync with the source code since it's still changing fairly frequently. It's the reason that we haven't considered embarking on a JS runtime yet either.

**Comment by micabytes** [comment] 2016-03-13 12:41
Do you see any major things changing in (as opposed to being added to) the specifications, beyond the Python speculation? I mean, I'd probably be happy to advocate for a markup language approach to text content, as discussed on the chat, but I can certainly see the rationale for not changing something that would affect existing work.

Adding new stuff should not be as big an issue for the spec. I think one would have to expect that not all backends might be fully compatible with the bleeding edge specs at all times.

**Comment by joethephish** [comment] 2016-03-19 15:43
Duplicate of <https://github.com/inkle/ink/issues/12>.

**Closed by joethephish** 2016-03-19 15:43 UTC
