### ISSUE TITLE
Sticky choices fail to repeat properly when diverted on the same line.

### ISSUE THREAD

**Issue by PicklesIIDX** [inkle/ink#112] opened 2016-06-21 05:13 UTC
Using the Inky IDE I encountered this issue while performing the tutorial.

If you use line endings in a specific way, choices will not be sticky.

This:

=== homers_couch
    +   [Eat another donut]
        You eat another donut. -> homers_couch

Produces the output:

Eat another donut
You eat another donut. 1: Eat another donut

and then I cannot make another choice.

However this:
=== homers_couch
    +   [Eat another donut] You eat another donut. -> homers_couch

and this:

=== homers_couch
    +   [Eat another donut] 
    You eat another donut. 
    -> homers_couch

work as expected.

This was found in the Inky IDE built and ran from commit 7ab5233 on OSX 10.11.5

**Comment by joethephish** [comment] 2016-06-21 06:20
Hrm, looks like a duplicate of <https://github.com/inkle/inky/issues/9>. But I managed to reproduce using your sample, thanks!

**Comment by joethephish** [comment] 2016-06-21 07:12
And fixed, thanks! Required changes in both ink and inky repos.

**Closed by joethephish** 2016-06-21 07:12 UTC
