### ISSUE TITLE
Windows line termination

### ISSUE THREAD

**Issue by joethephish** [inkle/ink#45] opened 2016-03-31 08:16 UTC
Before I jump in and accept [this code comment pull request](https://github.com/inkle/ink/pull/44) from @MattConrad, I was just wondering if anyone can help out with the source of the problem?

I'm not a Windows expert, though I understand the differences in line termination between platforms, broadly speaking. To be honest I was relatively surprised that me using `\n` everywhere worked okay, even when editing a story in Notepad, of all text editors.

Is the `.gitattributes` file the way to go to ensure Windows doesn't autoconvert, or is there something else we should be aware of? Should we simply being more line-ending agnostic in the compiler itself...? What's the "modern" way of handling this stuff?

**Comment by MattConrad** [comment] 2016-03-31 21:11
I only bumped into problems running the test suite, and this was only due to the multiline strings hardcoded for tests. Maybe more issues will pop out in other places later.

For me, the issue occurred because Git was set to automatically convert \n to \r\n. Turning that off fixed the problem. It looks like adding a .gitattribute file with "text eol=lf" should override this behavior [](https://git-scm.com/docs/gitattributes), but I didn't test it out. 

A .gitattribute wouldn't help if the file gets converted to \r\n some other way. I think this isn't super common, but Visual Studio does occasionally prompt me to resolve inconsistent line endings and I am in the habit of letting it do so. Probably caused by copying text from the clipboard that uses different line termination. Doesn't happen a lot, but does happen.

There is a .NET built-in value Environment.NewLine which represents the newline terminator for whatever system you're currently running. On Windows systems it is \r\n and on Unixy systems just \n. You could try replacing hardcoded \n values with Environment.NewLine and have platform aware line terminations everywhere.

However, as long as the issue is confined to running the tests, I don't think switching to Environment.NewLine is a good idea. Doing this would mean Windows users now have to always convert source code from /n to /r/n instead of never doing so, which isn't obviously an improvement, and switching might introduce other complications elsewhere. If other line terminator conflict issues start popping up in normal use of the engine, this might be worth revisiting.

I did think about adding a test suite function that automatically converted strings to consistent line endings before comparing them. Assert.MultilineStringsAreEqual() or something like that. Could still do this.

Anyway, that's what I've thought. Interested to hear what others think or have done in the past.

**Comment by joethephish** [comment] 2016-04-01 08:07
Thanks a lot - that sounds pretty good.

I'd be interested to hear from someone who's tested the gitattributes tweak, since that definitely sounds worthwhile if it works.

Beyond that, the best idea I've heard so far for changing in code is to preprocess the ink as it comes in (perhaps alongside the comment elimination pass), so convert `\r\n` into `\n` on Windows, so that by the time it hits the main code, it can just use `\n`. I like that solution because it's simple and doesn't muddy the main codebase. Still, the best solution is if we don't need a solution at all of course :-)

**Comment by MattConrad** [comment] 2016-04-03 19:47
I played around with .gitatrributes, specifically the instruction `* text eol=lf `.

Results were surprising. On my system, .gitattributes doesn't change files on checkout, only on checkin. Also, I find .gitconfig [core] autocrlf=true doesn't change files on checkout either, only on checkin. In both cases, only actively staged files are changed upon checkin. This is contrary to the documentation, docs say files will be changed in your working tree upon checkout.

I'm assuming my system is standard in this behavior. (I'd guess it is, but my git is kinda old, 1.9.5.msysgit.0.)

It looks like I called it wrong earlier. I don't think Git was introducing the CRLFs. I think Tests.cs must have been checked in with CRLFs. Now Tests.cs on `master` is LFs (mostly, there are few stray CRLFs still), and when I check it out all the tests run.

When I look around the source tree, some files are CRLF and some LF. For example \ink-engine-runtime\StoryState.cs is CRLF, \ink-engine-runtime\Story.cs is LF. This fits with the theory that Tests.cs got checked in as CRLF. Elsewhere it doesn't appear to be hurting anything.

The .gitattributes instruction above does override [core] autocrlf=true, so it would stop Windows developers from inadvertently overwriting Tests.cs with CRLFs later on. Over time the code base would converge on LFs instead of the current mix. I don't see much downside (developers will get warnings when checking in files that are getting converted to LFs). 

I'll add a pull request, if it seems like a plus you can merge.

**Comment by joethephish** [comment] 2016-04-03 19:59
Thanks for the investigation, that's really helpful. So the git repo will become more consistent which is great.

I guess there's the wider issue of whether the compiler copes with CRLF in general in user ink files, but perhaps that should be dealt with separately.

**Closed** 2016-04-03 19:59 UTC
Labels: help wanted

**Comment by MattConrad** [comment] 2016-04-03 22:29
Regarding CRLFs in .ink files, the playing around with Inklecate that I've done uses CRLFs. Mostly examples from the tutorial, not a huge amount of story code, but I haven't run noticed any issues yet.
