### ISSUE TITLE
Glue on Web export

### ISSUE THREAD

**Issue by markcmarino** [inkle/ink#183] opened 2016-09-13 08:00 UTC
The < > glue tags do not seem to work on the Web export ("export for web) from Inky (on Mac, viewed in Chrome). (They work fine within Inky.)

**Comment by y-lohse** [comment] 2016-09-13 08:12
Do you have a small example that shows the problem?

**Comment by joethephish** [comment] 2016-09-13 09:40
Note, this is a duplicate of [this issue](https://github.com/inkle/inky/issues/58) from the other repo.

**Comment by joethephish** [comment] 2016-09-17 10:29
Closing this issue since it's a duplicate, and it's clearly a problem either in inky or inkjs.

**Closed by joethephish** 2016-09-17 10:29 UTC
