### ISSUE TITLE
Bug passing floats as parameters in a divert 

### ISSUE THREAD

**Issue by bladecoder** [inkle/ink#162] opened 2016-08-24 11:42 UTC
Hi!

I have the next test:

```
How much do you give?
      * [$1] -> give(1.2)
      * [$2] -> give(2.5)
      * [Nothing] -> give(0)
      
      === give(amount) ===
          You give {amount} dollars.
          -> END
```

The output when selecting option 0 is:

`You give 12 dollars.`

The **correct** output should be:

`You give 1.2 dollars.`

Isn't it???

Cheers!

**Comment by joethephish** [comment] 2016-08-24 12:29
This one works for me!

![image](https://cloud.githubusercontent.com/assets/858967/17930529/9cc97448-69fe-11e6-9c34-1c7e0bc47149.png)

What environment are you using? Unity? JavaScript?

**Comment by bladecoder** [comment] 2016-08-24 12:52
I use inklecate from the command line:

![captura de pantalla de 2016-08-24 14-51-05](https://cloud.githubusercontent.com/assets/6229260/17931184/6355f5e0-6a0a-11e6-8b58-aebb43f01568.png)

**Comment by joethephish** [comment] 2016-08-24 12:59
Can anyone else reproduce this on Windows or Linux? (cc @kennethlarsen?) (it's working fine via command line for me on Mac, and inky uses the command line compiler in play mode internally)

**Comment by cduquesne** [comment] 2016-08-24 13:01
Hi,

I tried an even simpler test in Inky (Windows) and the result doesn't seem too good (tried via command line and I have the same error) :
![image](https://cloud.githubusercontent.com/assets/21159405/17931195/7ac3446c-6a0a-11e6-8c5c-a6f16d7388fa.png)
![image](https://cloud.githubusercontent.com/assets/21159405/17931204/877d6a8e-6a0a-11e6-8c94-e8220a12c612.png)

Full callstack :

```
Ink compiler had an unexpected error ☹

Exception non gérée : 
Ink compiler had an unexpected error ☹

System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   à Ink.StringParser.ParseFloat()
   à Ink.InkParser.ExpressionFloat()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.StringParser.OneOf(ParseRule[] array)
   à Ink.InkParser.ExpressionLiteral()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.StringParser.OneOf(ParseRule[] array)
   à Ink.InkParser.ExpressionUnary()
   à Ink.InkParser.Expression(Int32 minimumPrecedence)
   à Ink.InkParser.Expression()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   à Ink.InkParser.ExpressionFunctionCallArguments()
   à Ink.StringParser.Parse[T](SpecificParseRule`1 rule)
   à Ink.InkParser.DivertIdentifierWithArguments()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   à Ink.InkParser.MultiDivert()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.InkParser.c__AnonStorey7.<>m__0()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.StringParser.OneOf(ParseRule[] array)
   à Ink.InkParser.StatementAtLevel(StatementLevel level)
   à Ink.InkParser.c__AnonStorey6.<>m__0()
   à Ink.StringParser.ParseObject(ParseRule rule)
   à Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   à Ink.InkParser.StatementsAtLevel(StatementLevel level)
   à Ink.InkParser.Parse()
   à Ink.CommandLineTool.c__AnonStorey1.<>m__1()
   à Ink.CommandLineTool.TimeOperation(String opDescription, Action op)
   à Ink.CommandLineTool..ctor(String[] args)
   à Ink.CommandLineTool.Main(String[] args)
```

**Comment by kennethlarsen** [comment] 2016-08-24 13:04
Hmm. It works fine here on Linux using the editor.

**Comment by joethephish** [comment] 2016-08-24 13:05
Ouch! Thanks for the report @cduquesne. That's not good at alll...!

I wonder if there's some weird .NET version dependency stuff going on here, something to do with float parsing?! Odd that it works for some of us and not others.

**Comment by bladecoder** [comment] 2016-08-24 13:12
Well, it seems that is an inklekate problem since the generated .json is not correct. Look at the 12.0 and 25.0 values instead of 1.2 and 2.5:

`{"inkVersion":12,"root":[["^How much do you give?","\n",["ev","str","^$1","/str","/ev",{"*":".^.c","flg":20},{"c":[["ev",12.0,"/ev",{"->":"give"},null],{"#f":5}]}],["ev","str","^$2","/str","/ev",{"*":".^.c","flg":20},{"c":[["ev",25.0,"/ev",{"->":"give"},null],{"#f":5}]}],["ev","str","^Nothing","/str","/ev",{"*":".^.c","flg":20},{"c":[["ev",0,"/ev",{"->":"give"},null],{"#f":5}]}],null],"done",{"give":[{"temp=":"amount"},["^You give ",["G>",["ev",{"VAR?":"amount"},"out","/ev",null],"G<",null],"^ dollars.","\n","end",null],{"#f":3}],"#f":3}]}`

¿Maybe an error related with the .NET version?

**Comment by joethephish** [comment] 2016-08-24 13:14
Yup @bladecoder, and that's confirmed by @cduquesne's callstack.

**Comment by joethephish** [comment] 2016-08-24 13:20
If anyone wants to try and reproduce and track down this issue on Windows:

1. Load up **ink.sln**
2. Switch to the **Test** configuration (it loads up and plays **test.ink**)
3. Replace the contents of the **test.ink** file with the above ink
4. Run, and debug!

I'd suggest putting a breakpoint in `InkParser_Expression.cs`, in `ExpressionFloat()`. Watch the expression `remainingString` to see the current state of the parser in the ink file, and step into `ParseFloat()` to see what happens, in particular the string that's passed into `float.Parse`...

**Comment by cduquesne** [comment] 2016-08-26 08:40
Hi ! 

I had a look and it seems this problem is due to the fact that float.Parse is culture dependent. 
(makes sense given the fact that all the different issues were from non english testers)

It can be fixed by specifying the CultureInfo in the function arguments : 

`return float.Parse (leadingInt+"." + afterDecimalPointStr, System.Globalization.CultureInfo.InvariantCulture);`
instead of  
`return float.Parse (leadingInt+"." + afterDecimalPointStr);`

Which implies that in the Ink code everyone uses the international conventions ("." for decimal "," for thousands)

Does that fix seem ok ?

**Comment by joethephish** [comment] 2016-09-06 14:57
Fantastic, thanks for solving this, @cduquesne, and apologies for the delay in verifying the fix. Now integrated your suggestion in 343f6382b512f072e5e7296dbb25e4cf1107bf00.

**Closed by joethephish** 2016-09-06 14:57 UTC
Labels: bug
