### ISSUE TITLE
Compilation error in conditional blocks

### ISSUE THREAD

**Issue by bladecoder** [inkle/ink#163] opened 2016-08-26 09:57 UTC
Hi,

**inklecate** gives me a compilation error when using two conditionals, one after another:

```
VAR roll = 0
 
 { roll == 0:
    ~ roll = 2
 }
 
 { roll == 0:
    ~ roll = 1
 }
```

The error:

`ERROR: 'test-error.ink' line 7: Expected some kind of logic, conditional or sequence within braces: { ... } but saw ' roll == 0:'`

Is there anything wrong in my code or is a bug?

Cheers!

**Comment by joethephish** [comment] 2016-09-06 15:06
Odd, I can't reproduce this (on Mac), either in latest code on github, or in the latest release. I know it seems like a simple example already, but can you give me an even more specific repro? Platform, editor, exact thing you write on the command line etc?

**Comment by joethephish** [comment] 2016-09-11 10:17
Going to close this for now, feel free to re-open though if you still find it's not working for you!

**Closed by joethephish** 2016-09-11 10:17 UTC

**Comment by bladecoder** [comment] 2016-09-11 13:36
Ok, I was checking my test again and I found the error. My test had an invisible invalid character after the first condition. It was my fault, sorry :(

**Comment by joethephish** [comment] 2016-09-11 14:16
No problem, glad it's resolved!
